In [1]:
# 1. Data Encoding
# (1) Label Encoding
from sklearn.preprocessing import LabelEncoder
items = ['Betts', 'Seager', 'Turner', 'Muncy', 'Smith', 'Bellinger', 'Pederson', 'Bellinger']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('Encoded Values: ', labels)

Encoded Values:  [1 4 6 2 5 0 3 0]


In [2]:
# How to know which value is encoded to which number
print(encoder.classes_)

['Bellinger' 'Betts' 'Muncy' 'Pederson' 'Seager' 'Smith' 'Turner']


In [3]:
# get the string with encoded values (decoding)
print(encoder.inverse_transform([5, 2, 4, 3, 6, 0, 0]))

['Smith' 'Muncy' 'Seager' 'Pederson' 'Turner' 'Bellinger' 'Bellinger']


In [4]:
# (2) One-hot Encoding
from sklearn.preprocessing import OneHotEncoder
import numpy as np
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels = labels.reshape(-1, 1)

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)  # one-hot encoder gets 2-D array with only numbers as parameter
oh_labels = oh_encoder.transform(labels)
print('One-hot encoded data: ')
print(oh_labels.toarray())

One-hot encoded data: 
[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]


In [5]:
# get_dummies(): does one-hot encoding, but can also receive string values
import pandas as pd
df = pd.DataFrame({'item': items})
pd.get_dummies(df)

item_Bellinger  item_Betts  item_Muncy  item_Pederson  item_Seager  \
0               0           1           0              0            0   
1               0           0           0              0            1   
2               0           0           0              0            0   
3               0           0           1              0            0   
4               0           0           0              0            0   
5               1           0           0              0            0   
6               0           0           0              1            0   
7               1           0           0              0            0   

   item_Smith  item_Turner  
0           0            0  
1           0            0  
2           0            1  
3           0            0  
4           1            0  
5           0            0  
6           0            0  
7           0            0

In [8]:
# 2. Feature Scaling and Normalization
# (1) Standard Scalar - making Normal Distribution
from sklearn.datasets import load_iris
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
# mean, var for each column of DF
print('Before Scaling:')
print(iris_df.mean())
print(iris_df.var())
print()

# Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled_array = scaler.transform(iris_df)
iris_scaled_df = pd.DataFrame(data=iris_scaled_array, columns=iris.feature_names)
print('After Scaling:')
print(iris_scaled_df.mean())
print(iris_scaled_df.var())
# mean almost 0, var almost 1

Before Scaling:
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

After Scaling:
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [9]:
# (2) MinMaxScaler - the relative location of data between min and max (min: 0, max: 1)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled_array = scaler.transform(iris_df)
iris_scaled_df = pd.DataFrame(data=iris_scaled_array, columns=iris.feature_names)
# min, max of each column of scaled DF
print('After Scaling:')
print(iris_scaled_df.min())
print(iris_scaled_df.max())


After Scaling:
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
